version: '3'
services:
  app:
    build: 
      context: golang
      dockerfile: Dockerfile
    ports: 
      - 8080:8080 
    volumes:
      - ./golang:/app
    env_file: .env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/schema:/docker-entrypoint-initdb.d/schema

volumes:
  postgres: