CREATE TABLE IF NOT EXISTS wallets(
   id serial PRIMARY KEY,
   name VARCHAR (255) UNIQUE NOT NULL,
   currency VARCHAR (3) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories(
   id serial PRIMARY KEY,
   name VARCHAR (255) UNIQUE NOT NULL
);